# This workflow will install dependencies, create coverage tests and run Pytest Coverage Comment
# For more information see: https://github.com/MishaKav/pytest-coverage-comment/
name: pytest-coverage-comment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
# `contents` is for permission to the contents of the repository.
# `pull-requests` is for permission to pull request
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -e .

      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=quvac tests/ | tee pytest-coverage.txt
          SCORE_STR=$(grep "TOTAL" pytest-coverage.txt | awk '{print $4}')
          SCORE=${SCORE_STR%\%}
          echo $SCORE_STR
          echo $SCORE
          echo "SCORE_STR=$SCORE_STR" >> $GITHUB_ENV
          echo "SCORE=$SCORE" >> $GITHUB_ENV
          

    #   - name: Pytest coverage comment
    #     id: coverageComment
    #     uses: MishaKav/pytest-coverage-comment@main
    #     with:
    #       pytest-coverage-path: ./pytest-coverage.txt
    #       junitxml-path: ./pytest.xml
      
    #   - name: Check the output coverage
    #     run: |
    #       echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
    #       echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
    #       echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"

    #       echo "Coverage Warnings - ${{ steps.coverageComment.outputs.warnings }}"

    #       echo "Coverage Errors - ${{ steps.coverageComment.outputs.errors }}"
    #       echo "Coverage Failures - ${{ steps.coverageComment.outputs.failures }}"
    #       echo "Coverage Skipped - ${{ steps.coverageComment.outputs.skipped }}"
    #       echo "Coverage Tests - ${{ steps.coverageComment.outputs.tests }}"
    #       echo "Coverage Time - ${{ steps.coverageComment.outputs.time }}"

    #       echo "Not Success Test Info - ${{ steps.coverageComment.outputs.notSuccessTestInfo }}"
  
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
            auth: ${{ secrets.PYTEST_COVERAGE_COMMENT }}
            gistID: d6b0645fa035119a53bb6356d169c98b
            filename: quvac_coverage_badge.json
            label: Coverage Report
            message: is ${{ env.SCORE_STR }}
            valColorRange: ${{ env.SCORE }}
            maxColorRange: 90
            minColorRange: 30
            # message: ${{ steps.coverageComment.outputs.coverage }}
            # color: ${{ steps.coverageComment.outputs.color }}
            namedLogo: python